---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"] and ansible_distribution_version == "22.04"

  - name: install apache2 package
    apt: 
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache php
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution in ["Rocky", "Centos"] and ansible_distribution_version == "8.5"

  - name: install apache2 package
    dnf: 
      name: httpd
      state: latest
    when: ansible_distribution == "Rocky"

  - name: add php support for httpd
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "Rocky"

